apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: nginx-demo
