name: Kubernetes Deploy

on:
  push:
    branches:
      - main
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG}}

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Add sheel shript to apply k8s manifests
      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@main
        with:
          args: apply -f kubernetes/deployment.yaml
      
      - name: Deploy App(Service)
        uses: actions-hub/kubectl@main
        with:
          args: apply -f kubernetes/service.yaml

      - name: Deploy App(Ingress)
        uses: actions-hub/kubectl@main
        with:
          args: apply -f kubernetes/ingress.yaml
